#index:
#    path: /
#    controller: App\Controller\DefaultController::index
aboutMe:
  path: /aboutBecode
  controller: App\Controller\LearningController::aboutMe

showMyName:
  path: /
  controller: App\Controller\LearningController::showMyName

changeMyName:
  path: /changeMyName
  controller: App\Controller\LearningController::changeMyName
