#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /aboutMe
  controller: App\Controller\LearningController::aboutMe

showMyName:
  path: /showMyName
  controller: App\Controller\LearningController::showMyName

changeMyName:
  path: /
  controller: App\Controller\LearningController::changeMyName
